### ISSUE TITLE
any chances to update for voron v0 and blv printed part

### ISSUE THREAD

**Issue by tjengbudi** [Annex-Engineering/Quickdraw_Probe#4]
hello
any chance to update the project to support voron v0.1 and blv printed part one?

**Comment by Annex-Engineering** [comment]
We probably won't touch the BLv, no one internally has, or has plans to build one. 

The v0 is kind of in the same boat sadly. 

Due to some rude and vulgar comments made in the voron community, the member that traditionally has done the voron mods has decided to no longer do the work, and the rest of the team is busy with other internal projects, sorry. It's one of the downsides to such a small team, but it's also why we put out the cad for these parts.
